### ISSUE TITLE
Move to a monorepo structure

### ISSUE THREAD

**Issue by PaulRBerg** [PaulRBerg/prb-proxy#112]
## Tasks

- [ ] Set up pnpm monorepo structure (with [workspaces](https://pnpm.io/workspaces))
- [ ] Create mock packages starting from the table below
- [ ] Bring in [subgraph](https://github.com/sablier-labs/v2-subgraphs/tree/f063a82057a637667e1097379868d0d87f8cf7c7/packages/prb-proxy)

## Packages

| Path | Name |
|--------|--------|
| `packages/proxy` | `@prb/proxy` |
| `packages/frontend` | `@prb/proxy-frontend` |
| `packages/sdk` | `@prb/proxy-sdk` |
| `packages/subgraph` | `@prb/proxy-subgraph` |
| `packages/targets` | `@prb/proxy-targets` |

**Comment by scorpion9979** [comment]
What are the packages are you thinking to have as part of the monorepo?

**Comment by PaulRBerg** [comment]
@scorpion9979 I've updated the OP.
